version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: es01
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic


networks:
  elastic:
    driver: bridge